### PR TITLE
Include extra headers to resolve compiler errors on Visual Studio 2010

### PR DESCRIPTION
**Pull request by bkevelham**
Include iterator and StdVector (http://eigen.tuxfamily.org/dox/group_TopicStlContainers.html) headers to resolve compiler errors in Visual Studio 2010

### CODE REVIEW

**Comment by janbender** [comment]
Hi, 

for me it works in Visual Studio 2010 if I only add the line

#include <iterator>

in the file Demos/Utils/IndexedFaceMesh.h. The other two includes were not necessary. Can you please try this and modify your pull request?

Jan

**Comment by bkevelham** [comment]
If I do that I get a list of errors along the following lines:

    1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\vector(870): error C2719: '_Val': formal parameter with __declspec(align('16')) won't be aligned
    1>          d:\libraries\positionbaseddynamics\demos\clothdemo\TriangleModel.h(42) : see reference to class template instantiation 'std::vector<_Ty,_Ax>' being compiled
    1>          with
    1>          [
    1>              _Ty=PBD::TriangleModel::BendingConstraint,
    1>              _Ax=Eigen::aligned_allocator<PBD::TriangleModel::BendingConstraint>
    1>          ]

Inclusion of StdVector resolves this for me.

**Comment by janbender** [comment]
Which version of Eigen do you have? Is it a Win32 or Win64 build?

**Comment by janbender** [comment]
Ok, this seems to be a Win32 issue.

**Comment by bkevelham** [comment]
I can confirm I was indeed on Win32. And the Eigen version was the one in `extern`. Glad you could reproduce it. Thanks!

**Pull request merged**
