### PR TITLE
Make AntTweakbar and glew compile on OSX

### PR DESCRIPTION
**Pull request by meshula**
Here's a few tweaks to port the system to OSX.

### CODE REVIEW

**Comment by astefanutti** [comment]
I'm getting the following error while building the project with make on El Capitan:
```
Linking CXX executable bin/BarDemo
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/BarDemo] Error 1
make[1]: *** [Demos/BarDemo/CMakeFiles/BarDemo.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by meshula** [comment]
I'll have a look and see if I can reproduce that. X11 is a surprising dependency. Maybe I've got an old X11/Quartz install that is masking the issue.

**Comment by astefanutti** [comment]
I tried installing the latest Quartz version though I still faced the same issue. It looks like CMake is adding `-lX11` to the link instructions. After removing the X11 reference in the `AntTweakBar` CMake configuration:
```
diff --git a/extern/AntTweakBar/CMakeLists.txt b/extern/AntTweakBar/CMakeLists.txt
index 271f8d6..69b4b3c 100644
--- a/extern/AntTweakBar/CMakeLists.txt
+++ b/extern/AntTweakBar/CMakeLists.txt
@@ -61,7 +61,7 @@ add_library(AntTweakBar STATIC ${ATB_HEADERS} ${ATB_SOURCES})
 set_target_properties(AntTweakBar PROPERTIES FOLDER "External Dependencies")
 
 if (UNIX)
-	target_link_libraries(AntTweakBar X11)
+	target_link_libraries(AntTweakBar)
 endif()
 
 set(AntTweakBar_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include
```
I got the following error:
```
Linking CXX executable ../../BarDemo
Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      PBD::MiniGL::keyboard(unsigned char, int, int) in MiniGL.cpp.o
  "_glutMouseWheelFunc", referenced from:
      PBD::MiniGL::init(int, char**, int, int, int, int, char*) in MiniGL.cpp.o
  "_glutSetOption", referenced from:
      PBD::MiniGL::init(int, char**, int, int, int, int, char*) in MiniGL.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [BarDemo] Error 1
make[1]: *** [Demos/BarDemo/CMakeFiles/BarDemo.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by janbender** [comment]
Thanks for your help. Since astefanutti seems to have some problems, I will try to find a Mac to test the changes before I merge the code. However, this can take a few days.

**Comment by meshula** [comment]
So there is a problem on OSX 10.11, I'm not sure if the problem exists on earlier versions of OSX. The problem is that the symbols you mention, glutLeaveMainLoop, glutMouseWheelFunc, and glutSetOption are not published symbols in the system GLUT framework. That's a bug on the Apple side of things.

If you guard the use of those three functions in your test program with an ifdef vs. __APPLE__, then the program will compile and link and run properly. Obviously you will lose the mouse wheel functionality. Command-Q to quit still works, so the glutLeaveMainLoop call is not strictly necessarily. Finally the glutSetOption call does not affect the operation of the program in any way I can discern, so it's probably safe to omit it on OSX until some future date when GLUT on OSX is fixed.

Hope this helps.

**Comment by astefanutti** [comment]
@meshula thanks a lot, that works. I'm able to compile and run the demos. I'm a bit surprised they run very slow on my machine though that's another issue I guess.

**Comment by meshula** [comment]
I haven't profiled, it would be interesting to know where the time has gone!

**Pull request merged**
